# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zarr
subtitle: chunked, compressed, N-dimensional arrays

description: >- # this means to ignore newlines until "baseurl:"

  Zarr is an open source project developing specifications and
  software libraries for storage of data that is structured as
  N-dimensional typed arrays (also known as tensors) in a way that is
  compatible with parallel and distributed computing applications.

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

analytics:
  provider: "google"
  google:
    tracking_id: "G-BCRR9QE7Z0"
    anonymize_ip: true

github_username:  zarr-developers
gitter_url: https://gitter.im/zarr-developers/community

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# https://github.com/mmistakes/minimal-mistakes/blob/641ca6f3d8cd8fb0ae24e4f77b2e62a44a65e53b/_config.yml
logo: android-chrome-512x512.png
search: true
search_full_content: true
social:
  type: Organization
  name: Zarr
  links:
    - "https://bsky.app/profile/zarr.dev"
    - "https://github.com/zarr-developers"

footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/zarr.dev"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://fosstodon.org/@zarr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zarr-developers"
    - label: "Zulip"
      icon: "fas fa-comments"
      url: "https://ossci.zulipchat.com/"

head_scripts:
  - assets/js/language_switcher.js
